### ISSUE TITLE
YOUR-USERNAME follows GitHub Flow

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/dev-mar-6#20]
# Orlando, FL

- [x] create a **branch**
- [x] add some **commits**
- [x] open a *pull request*
- [ ] collaborate
- [ ] `merge` with 👍

**Comment by MichaelKennedy39** [comment]
Sorry - got behind a little - need help on the self-assign (I created an issue and a branch ok but what was I supposed to do in between ?
@MichaelKennedy39

**Comment by githubteacher** [comment]
@MichaelKennedy39 head on over to the Gitter Chat: https://gitter.im/dev-mar-6/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
